### ISSUE TITLE
Post build instructions?

### ISSUE THREAD

**Issue by ekristen** [rancherpi/rancher-arm64#2]
Can you post the scripts or the step by step for what you are doing to actually build these?

**Comment by antmanler** [comment]
Currently I try to build the images that do not have official arm64 support on scaleway arm64 server.
For each image, check out its project from upstream then modify build scripts(+ source code sometimes) to get it work on a arm64 then push it to docker hub.

Feature work I'm working on is to build arm64 images on my x86 laptop locally, this might help more people to reproduce these build steps.

**Comment by ekristen** [comment]
That’s what I’m interested in. How you are doing the build, please share once you have them.

**Comment by ekristen** [comment]
@antmanler any chance you can post the steps you take and the modifications you make to build these images?

**Comment by antmanler** [comment]
The repo was organised by branch to follow rancher's releases, currently the full modifications are listed in [patch](https://github.com/rancherpi/rancher-arm64/tree/v2.0.8-arm64/patch) as well as the [build script](https://github.com/rancherpi/rancher-arm64/blob/v2.0.8-arm64/build.sh)

BTW, rancher will support arm officially soon https://github.com/rancher/rancher/issues/16461
