### ISSUE TITLE
100% CPU on Rock64

### ISSUE THREAD

**Issue by j2l** [rancherpi/rancher-arm64#3]
Thx for pushing this.
Just to let you know that it used 100% of all CPU cores (ROCK64 has 4) on DietPi Debian OS.
I know it will be replaced soon by [official image](https://github.com/rancher/os) (BTW, I don't get how to docker run it yet).

**Comment by antmanler** [comment]
recommend have a look https://github.com/ibuildthecloud/k3s

The lightweight k8s, which runs on raspberry pi smoothly

**Comment by j2l** [comment]
Thank you very much!
